version: 2.1
jobs:
  build-templates:
    docker:
      - image: unidays/dotnet-core-sdk-nuget:2.2
    steps:
      - checkout
      - run:
          name: Build and test templates
          command: dotnet test -c Release
      - run:
          name: Package templates
          command: nuget pack ./UD.Lambda.Templates.nuspec
      - run:
          name: Push package to MyGet
          command: find . -iname "*.nupkg" -exec dotnet nuget push '{}' -s https://www.myget.org/F/unidays-release/api/v2/package -k $MYGET_API_KEY \;
workflows:
  version: 2
  build-publish:
    jobs:
      - build-templates
